#!/bin/bash

curl https://tester.dm.unibo.it/siamis/latex/plenaries.tex               -o plenaries.tex
curl https://tester.dm.unibo.it/siamis/latex/minitutorials.tex           -o minitutorials.tex

curl https://tester.dm.unibo.it/siamis/latex/program.tex                 -o program.tex
curl https://tester.dm.unibo.it/siamis/latex/program_glance.tex          -o program_glance.tex

curl https://tester.dm.unibo.it/siamis/latex/speakers_and_organizers.tex -o speakers_and_organizers.tex

# Book of abstracts
curl https://tester.dm.unibo.it/siamis/latex/minisymposia.tex            -o minisymposia.tex
curl https://tester.dm.unibo.it/siamis/latex/contributed.tex             -o contributed.tex
curl https://tester.dm.unibo.it/siamis/latex/posters.tex                 -o posters.tex

curl https://tester.dm.unibo.it/siamis/latex/doors.tex                   -o doors.tex
