#!/bin/bash

curl https://tester.dm.unibo.it/siamis/latex/plenaries.tex 
curl https://tester.dm.unibo.it/siamis/latex/minitutorials.tex 

curl https://tester.dm.unibo.it/siamis/latex/minisymposia.tex 
curl https://tester.dm.unibo.it/siamis/latex/contributed.tex 
curl https://tester.dm.unibo.it/siamis/latex/posters.tex 

curl https://tester.dm.unibo.it/siamis/latex/program.tex 


