# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d167f9210a30c5bd2dd574786e82b79d742cc5a46306b5be557122bd99dcd93ec775cd0d5de6deffee514c6b81a9076738163f22a9a57ec026bb84827b84b03

test:
  secret_key_base: e043f59f920c02cb70842b87ed23477856d4fef5623b44082b649ad712f7413ddd3583041a8e3fae4f1e844827e0eb88e3a5a8a908b37a4cd9d878287cea12d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SIAMIS_SECRET_KEY_BASE"] %>
